modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/multiple_server_lists/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "multiple_server_lists"
version = "${version}"
displayName = "Multiple Server Lists"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.multiple_server_lists]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiple_server_lists]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiple_server_lists]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
